name: Docker build and push

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64,arm'

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
          install: true

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.actor }}/dapr-sqlite-statestore
          tags: |
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=ref,event=branch
            type=edge,branch=main

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Bake: build and push"
        uses: docker/bake-action@v2.3.0
        with:
          push: true
          files: |
            docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
